const cues = {

1: "a/ I’m currently working as a pharmacist and living in a peaceful coastal area. Professionally, I value precision and responsibility, because even minor errors can have serious consequences. Personally, I’m reflective and goal-oriented. I constantly try to improve myself, whether through learning English or exploring technology. I believe sustainable growth comes from consistency rather than bursts of motivation. \n b/ I’m a pharmacist living in a coastal town. I’m quite reflective and disciplined, and I focus strongly on personal growth. Besides work, I enjoy learning English and developing new skills because I believe continuous improvement shapes long-term success.",

2: "a/ I live with my husband and our twin children. Interestingly, my husband used to be my best friend in high school, so our relationship is built on deep trust. Raising twins can be demanding, but it has taught me patience and emotional resilience. Despite our busy schedules, we prioritise family time every evening. \n b/ I live with my husband and twin children. My husband was my high school best friend, so we understand each other well. Although parenting twins can be challenging, our home is warm and supportive.",

3: "a/ I prefer a small circle of close friends rather than a large social network. I value meaningful conversations over casual interactions. My friends are supportive and honest, and we often discuss personal development or work-related challenges. I believe strong friendships are built on mutual growth. \n b/ I keep a small group of close friends. We focus on deep conversations and emotional support. I prefer quality over quantity in relationships.",

4: "a/ I’d like to talk about my husband. He is calm and analytical, which balances my more reflective personality. Whenever I face pressure at work, he helps me approach situations logically instead of emotionally. His stability creates a sense of security in our family. \n b/ I’d like to describe my husband. He is calm and rational, and he always helps me stay objective when I feel overwhelmed. His emotional stability is something I deeply appreciate.",

5: "a/ As a pharmacist, my role involves more than dispensing medicine. I need to ensure prescriptions are accurate and advise patients on safe usage. The job requires scientific knowledge, strong concentration, and empathy. Although it can be stressful, it is meaningful because it directly impacts people’s health. \n b/ I work as a pharmacist. My job requires precision, responsibility, and patient communication. It can be stressful, but it’s rewarding because I help people manage their health safely.",

6: "a/ I’m learning English to broaden both my professional and intellectual horizons. It allows me to access global knowledge, especially in technology and healthcare. Additionally, thinking in another language enhances my cognitive flexibility. I see English not just as a skill, but as a tool for expansion. \n b/ I’m learning English to expand my knowledge and career opportunities. It gives me access to international resources and challenges me to think more critically.",

7: "a/ My typical day starts quite early because I prepare breakfast for my twins before going to work. At the pharmacy, I focus on accuracy and patient consultation, which requires both concentration and empathy. After work, I dedicate time to my family, helping my children with simple learning activities. In the evening, I usually unwind by reading or working on small creative projects. Although my schedule is demanding, it feels purposeful. \n b/ I usually start my day early to prepare for work and my children. At the pharmacy, I focus on patient care. In the evening, I spend time with my family or relax with reading. My routine is busy but meaningful.",

8: "a/ Today has been fairly productive. I handled several prescriptions and supported customers who needed detailed advice. Some situations required patience, especially when explaining dosage instructions. After work, I plan to spend the evening with my family and possibly review some English materials. I try to end each day by reflecting briefly on what I learned or handled well. \n b/ Today has been productive. I worked at the pharmacy and assisted customers with medication advice. Later, I’ll spend time with my family and maybe review some English. I like finishing my day calmly.",

9: "a/ With my friends, I usually engage in meaningful activities rather than casual entertainment. We sometimes organise small charity events or simply meet to discuss personal growth and life challenges. I appreciate friendships that encourage reflection and support rather than superficial interaction. These conversations help me maintain emotional balance. \n b/ I usually spend time talking deeply with my friends or participating in small charity activities. I value supportive friendships more than social gatherings.",

10: "a/ In my free time, I prefer calm and creative activities. I enjoy crocheting handmade items, especially for my children, because it allows me to express care in a tangible way. I also read historical books and explore new ideas in technology. These quiet hobbies help me recharge after intense workdays. \n b/ I enjoy crocheting, reading, and learning about technology. These quiet activities help me relax and regain mental clarity after work.",

11: "a/ One of my favourite hobbies is crocheting. I started it as a way to relax, but over time it became a meaningful creative outlet. I’ve even made handmade clothes and small items for my children. The process requires patience and attention to detail, which suits my personality. It’s therapeutic and productive at the same time. \n b/ My main hobby is crocheting. It helps me relax and express creativity. I enjoy making handmade items for my children because it feels personal and meaningful.",

12: "a/ For the rest of today, I plan to spend quality time with my family. We might go for a short walk or simply talk about our day. Later in the evening, I may review some English materials or adjust a small project I’m working on. I try to maintain a balance between productivity and relaxation. \n b/ Later today, I’ll spend time with my family and possibly review some English. I prefer evenings that are calm but still productive.",

13: "a/ I usually feel tired after emotionally demanding days at work, especially when I need to manage difficult communication situations. Mental fatigue affects me more than physical tiredness. However, once I return home and spend time with my children, I often feel re-energised. Emotional support makes a significant difference. \n b/ I feel tired mainly after stressful communication at work. Mental pressure drains me more than physical tasks. Spending time with my family helps me recover quickly.",

14: "a/ I feel stressed when I face communication barriers, particularly when explaining medical information clearly. Accuracy is essential in my profession, so I take responsibility seriously. However, instead of avoiding stress, I treat it as feedback that I need to improve certain skills. That mindset helps me grow rather than feel overwhelmed. \n b/ I feel stressed when communication becomes challenging at work. However, I try to see stress as motivation to improve rather than something negative.",

15: "a/ Yesterday was a fairly typical working day for me. I spent most of the morning at the pharmacy assisting customers and checking prescriptions carefully. In the afternoon, I had to explain medication instructions to an elderly patient, which required patience and clarity. After work, I went home, had dinner with my family, and helped my children with their bedtime routine. It was simple but meaningful. \n b/ Yesterday, I worked at the pharmacy and assisted several customers. After work, I had dinner with my family and spent time with my children. It was an ordinary but fulfilling day.",

16: "a/ Last weekend, I spent most of my time with my family. We took our twins to a playground near the beach, and watching them enjoy themselves was incredibly rewarding. In the evening, after they went to sleep, I quietly reviewed some improvements for a small website project. It was a balanced weekend — family bonding during the day and personal growth at night. \n b/ Last weekend, I took my children to a playground and enjoyed family time. In the evening, I worked briefly on a website project. It was relaxing and productive.",

17: "a/ The last time I spoke with my mother, we discussed balancing work and family life. I sometimes feel pressure managing both my profession and motherhood. She reminded me that progress is more important than perfection and encouraged me to be kinder to myself. That conversation helped me feel reassured and emotionally supported. \n b/ When I last talked to my mother, we discussed work-life balance. She advised me not to pursue perfection but steady progress. Her words gave me comfort.",

18: "a/ One of my most meaningful memories was travelling alone to Jeju Island after a difficult breakup. Although I felt emotionally exhausted, I unexpectedly had the chance to help an elderly tourist communicate with a shop owner. After resolving the misunderstanding, I received a small gift as a thank-you. That moment reminded me that even during personal hardship, I could still contribute positively to others. \n b/ A good memory was my solo trip to Jeju Island. I helped an elderly tourist communicate with a shop owner, and I was thanked with a small gift. It reminded me that kindness matters.",

19: "a/ The last time I cooked something special was during Lunar New Year. My family prepared a simple vegetarian meal to honour our ancestors. I made stir-fried vegetables and tofu soup. Although the dishes were modest, the atmosphere was meaningful. Cooking in that context felt less like a task and more like an expression of gratitude and tradition. \n b/ Recently, I cooked a vegetarian meal for Lunar New Year. It wasn’t complicated, but it carried cultural and emotional significance for my family.",

20: "a/ The last time I visited friends, we gathered to discuss a small charity project at a provincial hospital. Unexpectedly, heavy rain disrupted our initial plan to distribute food in the cafeteria. Instead of giving up, we reorganised and requested permission to deliver meals directly to patients’ rooms. It was exhausting but deeply satisfying. \n b/ When I last visited my friends, we organised charity work at a hospital. Due to bad weather, we adjusted our plan and delivered food directly to patients. It was meaningful.",

21: "a/ The last time I went to the cinema was with my husband. We rarely have time alone, so it felt refreshing. The film itself was enjoyable, but what I appreciated most was the opportunity to reconnect without distractions. As parents of twins, small moments like that become surprisingly valuable. \n b/ I last went to the cinema with my husband. It was a simple outing, but we valued the quiet time together away from daily responsibilities.",

22: "a/ The last programme I watched was a short documentary about healthcare systems. As a pharmacist, I’m naturally interested in medical topics. It highlighted the importance of patient education and responsible medication use. I found it informative and professionally relevant, and it encouraged me to reflect on my own practice. \n b/ Recently, I watched a healthcare documentary. It focused on patient education, which relates closely to my profession. I found it both useful and thought-provoking.",

23: "a/ In the future, I plan to improve my English to a more advanced level so I can communicate confidently in professional settings. As a pharmacist, I sometimes interact with foreign customers, and I want to handle those situations more fluently. I also hope to develop more digital projects independently. For me, continuous learning is not just a goal but a mindset. \n b/ I’m planning to improve my English and develop more digital projects in the future. I believe continuous learning helps me grow both professionally and personally.",

24: "a/ I live in a coastal area of Lam Dong province. What makes it special is the contrast between the sea and the nearby highlands. The atmosphere is relatively peaceful, which suits my personality. Living near the sea gives me a sense of openness and calm, especially after stressful working days. \n b/ I live in a coastal area in Lam Dong. It’s peaceful and close to both the sea and the mountains. I appreciate the calm environment.",

25: "a/ One famous place in my province is Đà Lạt. It’s well known for its cool climate, pine forests, and peaceful scenery. Many people visit to escape the heat and busy city life. The atmosphere encourages relaxation and reflection, which is why I personally enjoy spending time there with my family. \n b/ A famous place in my province is Đà Lạt. It’s known for its cool weather and peaceful atmosphere, making it a popular destination for relaxation.",

26: "a/ My favourite place is Đà Lạt because of its calm and refreshing environment. The cool air and green landscapes create a sense of emotional balance for me. Whenever I feel overwhelmed, spending time there helps me slow down and think more clearly. It feels like a reset button for my mind. \n b/ My favourite place is Đà Lạt. Its cool climate and peaceful scenery help me relax and regain mental clarity.",

27: "a/ The room I’m in is simple and well-organised. It has soft lighting and minimal decoration, which helps me concentrate. I prefer tidy spaces because they reduce distraction and create mental clarity. As someone who handles responsibility daily, I find that a calm environment supports both focus and emotional balance. \n b/ The room is quiet and neatly arranged. I prefer simple spaces because they help me focus and feel mentally organised.",

28: "a/ Today, I travelled here by motorbike. Since I live near the sea, the wind was slightly strong, so I had to stay focused on the road. During the journey, I was mentally preparing myself for the exam. I felt a mixture of nervousness and determination, which is quite natural before an important event. \n b/ I came here by motorbike. The wind was quite strong, so I had to be careful. I felt slightly nervous but determined.",

29: "a/ In the future, I’d like a house that offers both comfort and tranquility. A spacious kitchen is important because I value family meals. I would also love a small creative corner where I can crochet or work on digital projects. More than luxury, I prioritise safety, warmth, and a sense of connection. \n b/ I’m looking for a peaceful house with a comfortable kitchen and a small creative space. Comfort and family connection matter more to me than luxury.",

30: "a/ A typical Vietnamese meal is balanced and shared among family members. It usually includes rice, a vegetable dish, soup, and some protein such as fish or pork. What I appreciate most is not only the flavour but also the atmosphere. Mealtime is when everyone gathers, talks about their day, and reconnects. It reflects how food in Vietnam is strongly linked to family values. \n b/ A Vietnamese meal usually includes rice, vegetables, soup, and some protein. More importantly, it’s a time for family members to gather and share their day.",

31: "a/ Vietnamese food is fresh, diverse, and well-balanced. We use a lot of herbs and natural ingredients, which create distinctive flavours without being too heavy. In addition, our cuisine varies significantly from region to region. Personally, I value how meals are not just about eating but about strengthening relationships within the family. \n b/ Vietnamese food is fresh and flavourful, with many herbs and natural ingredients. It’s also closely connected to family bonding.",

32: "a/ In Vietnam, football is by far the most popular sport. Major matches often bring people together, whether in cafés or at home, creating a strong sense of community. Besides football, badminton and volleyball are also common because they are accessible and affordable. Sports are not only entertainment but also a way to build national pride. \n b/ Football is the most popular sport in Vietnam. It brings people together and creates a strong community spirit. Badminton and volleyball are also common.",

33: "a/ Reading preferences in Vietnam vary depending on age and interests. Younger people tend to read online articles and self-development books, while older generations may prefer historical or literary works. Personally, I appreciate historical books because they provide cultural depth and perspective. Reading, in general, is increasingly shifting toward digital platforms. \n b/ Many young people read online content or self-improvement books, while older readers prefer history or literature. Digital reading is becoming more common.",

34: "a/ In Vietnam, motorbikes are the most flexible and practical means of transportation, especially in cities. However, for longer distances or family trips, travelling by car or plane is more comfortable and safer. I believe the best option depends on the purpose of the trip. Convenience, safety, and budget should all be considered. \n b/ Motorbikes are convenient for short distances, but cars or planes are better for longer trips. The best way depends on safety and purpose.",

35: "a/ I’m interested in travel because it allows me to gain new perspectives and reset emotionally. Experiencing different environments broadens my understanding of people and culture. I once travelled alone during a challenging period in my life, and that journey helped me regain confidence. Travel, for me, is not just leisure but personal growth. \n b/ Travel helps me gain new perspectives and emotional balance. It allows me to grow and understand life beyond my routine.",

36: "a/ Today, the weather is slightly windy since I live near the sea. The temperature is moderate, not too hot, which makes it quite comfortable. I actually appreciate mild weather because it helps me stay focused and calm. Extreme heat, on the other hand, can be quite draining. \n b/ Today is slightly windy but comfortable. I prefer moderate weather because it helps me feel calm and focused.",

37: "a/ My favourite season is when the weather becomes cooler, especially like the climate in Đà Lạt. Cooler temperatures create a peaceful atmosphere and allow me to think more clearly. Since my job can be mentally demanding, I find that calm weather helps me recharge emotionally and physically. \n b/ I prefer cooler seasons, especially weather like in Đà Lạt. It feels peaceful and helps me relax mentally.",

38: "a/ My first school was a small primary school near the seaside. It wasn’t modern, but it felt safe and welcoming. I was a quiet child, so I often preferred reading or observing rather than participating in noisy activities. Looking back, that environment shaped my reflective personality and my love for learning. It taught me that confidence can develop gradually over time. \n b/ My first school was small and simple but very welcoming. I was a quiet student who enjoyed reading. It helped shape my reflective personality.",

39: "a/ Today I’m wearing something simple and comfortable. As a pharmacist and a mother, practicality matters more to me than fashion. I prefer neat and modest clothing that allows me to move easily throughout the day. I believe confidence comes more from how you carry yourself than from expensive outfits. \n b/ I’m wearing simple and comfortable clothes today. I prefer practical outfits that make me feel confident and relaxed.",

40: "a/ I’m particularly drawn to music from the 1980s because of its emotional depth and timeless quality. One song I truly appreciate is Vincent, also known as “Starry, Starry Night.” Its gentle melody and poetic lyrics create a reflective atmosphere. After stressful days at work, this type of music helps me slow down and reconnect with my emotions. \n b/ I enjoy 1980s music, especially Vincent. Its calm melody and meaningful lyrics help me relax after work.",

41: "a/ One singer I admire is Don McLean, because his songs are thoughtful and poetic. His music focuses more on storytelling than commercial trends. I appreciate artists who express emotion honestly, and his work feels timeless. Listening to his songs often gives me a sense of calm reflection. \n b/ I admire Don McLean because his songs are poetic and meaningful. His music feels sincere and timeless.",

42: "a/ One film I found meaningful is The Pursuit of Happyness. It portrays perseverance in the face of financial and emotional hardship. What impressed me most was the main character’s resilience and dedication to his son. As a parent, I deeply relate to the idea that sacrifice and persistence can eventually lead to a better future. \n b/ I like The Pursuit of Happyness because it highlights resilience and parental dedication. It’s both inspiring and emotionally powerful.",

43: "a/ My favourite film star is Will Smith, especially because of his role in The Pursuit of Happyness. I admire how he portrays determination and emotional strength in a very authentic way. Beyond acting, he often speaks about discipline and self-development, which I personally value. \n b/ I admire Will Smith because he often plays strong and resilient characters. His performances feel authentic and inspiring.",

44: "a/ One book I truly appreciate is Việt Nam sử lược. It provides a broad overview of Vietnamese history and cultural development. I enjoy reading it because it helps me understand my roots and see how historical events shape modern society. As someone who values reflection, history gives me a deeper sense of perspective. \n b/ I appreciate Việt Nam sử lược because it gives a clear overview of Vietnamese history and cultural roots."
};